### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by nathanleiby**
This runs unity unit tests and produces a WebGL build, following instructions here: https://github.com/webbertakken/unity-actions

### CODE REVIEW

**Comment by nathanleiby** [comment]
I notice these all the builds (well, at least Windows and WebGL) have at least one issue. The `TextMeshPro` text isn't showing up, leading to a menu UI that's quite confusing/unusable if you don't have it memorized.

image

As a hack -- just press enter a bunch and enter a battle :D At that point, the game seems to run fine!

--

Not sure of the cause yet, will have to investigate further.

**Comment by nathanleiby** [comment]
Verified that https://github.com/CleverGameDev/Cleverfall/pull/27/commits/a0c43cd03891800b1053c75a7111c86d56b96f51 fixed the text mesh issues! 

(Also found more evidence that it's a common mistake: https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues/72)

**Comment by nathanleiby** [comment]
Just tested it out on MacOS as well. To get that build to run I had to first run

```
chmod +x StandaloneOSX.app/Contents/MacOS/Cleverfall
```

to make it executable. It then opens, but you hit this error:

Screenshot_5_1_20__3_27_PM

I also had to allow running an app from an unidentified developer via security and privacy (see: https://support.apple.com/en-us/HT202491) to work around

**Comment by nathanleiby** [comment]
Gonna just merge this one in! The main remaining consideration is whether we'll approach the `1000min/month` limit for github actions. Probably not, but if so we can reduce the amount of builds created within a branch.

**Comment by peternga** [comment]
I was just looking at it and was going to say LGTM!

**Comment by peternga** [comment]
I think I'll need to read up on what TextMesh Pro does though

**Comment by nathanleiby** [comment]
@peternga my understanding is that TextMeshPro is the unity endorsed way to work with rich text in your UIs https://blogs.unity3d.com/2018/10/16/making-the-most-of-textmesh-pro-in-unity-2018/

I learned about it watching some YouTube tuts, but don't know too much otherwise

**Pull request merged**
