### PR TITLE
Character select

### PR DESCRIPTION
**Pull request by nathanleiby**
Here's a demo of how things currently look.

Getting here was a lot harder than I expected! Challenges described in https://github.com/CleverGameDev/Cleverfall/pull/16/commits/462038c296f8a1a5e4a128752b293eb557802912 

character-select

### CODE REVIEW

**Comment by nathanleiby** [comment]
@peternga @TheRealBenjiLi this isn't ready to merge yet, but would love to know if you think this is the right direction. I'm trying to closely follow Towerfall UX for joining via a character select lobby and otherwise shared menu navigation. 

https://docs.google.com/drawings/d/1sz9mVoZGK6wpIQaLspmDt3oXd9kEx896oMgVC6WzvnE/edit

Some other games like overcooked assign a "first player" who does all menu nav except for character selection.

**Comment by peternga** [comment]
I only did a quick skim, but it looks good to me. Some questions: is it correct to say that we're currently identifying players by the existence of HumanPlayer-tagged GameObjects? When are these GameObjects created? Are they always available?

**Comment by nathanleiby** [comment]
@peternga 

> is it correct to say that we're currently identifying players by the existence of HumanPlayer-tagged GameObjects?

Yes, that's correct! 

> When are these GameObjects created?

The `PlayerInputManager` (https://docs.unity3d.com/Packages/com.unity.inputsystem@0.2/api/UnityEngine.InputSystem.Plugins.PlayerInput.PlayerInputManager.html) instantiates new `HumanPlayer` game objects. Each `HumanPlayer` gets a `PlayerInput` attached to it which refers to that player's specific input device.

I'm using the default Join Behavior to add a player when any button is pressed on a new controller.
image

For example:
1. person clicks a keyboard key => 1st `HumanPlayer` spawns
2. person presses a button on a controller =>2nd `HumanPlayer` spawns
3. person presses a button on a 2nd controller =>3rd `HumanPlayer` spawns

We can choose other Join Behaviors to more strictly limit when players join or leave, which might be worth trying. I would like if users were added/removed only in the "Character Select" UI.

> Are they always available?

They are available within a scene. To move them across scenes, I used `DontDestroyOnLoad`. Another approach suggested is additive scene loading. (see some links in the Trello ticket https://trello.com/c/aZeRpXzj/32-cleverfall-allow-selecting-a-character)

**Comment by nathanleiby** [comment]
@peternga I rebased this against your last change and a few polish commits

- made character color match the inside out character https://github.com/CleverGameDev/Cleverfall/pull/16/commits/c1d396868fd25b9fdd9027543ad8d2c2d0f97ec9
- allow player to respawn once killed by a jump https://github.com/CleverGameDev/Cleverfall/pull/16/commits/c8119a0580e8647392b95750b15e943763a6be51

respawn

Going to merge, as I think things are in a reasonably good state.

**Pull request merged**
