### PR TITLE
Hazard: Noxious Gas

### PR DESCRIPTION
**Pull request by emmanent**
Introducing the first hazard: Noxious Gas! This purple particle effect will kill players on contact! At the moment, it's not visible to players just yet.

### CODE REVIEW

**Comment by nathanleiby** [comment]
Very cool stuff! I opened up stuff in the editor and was able to throw the noxious gas into a game scene and it killed the player. The purple blob of doooom.

Immediate thoughts:
1. the gas seems to collide 3x very quickly and kill the player, resulting in a chunky audio effect and instadeath. Might we add a "can only do damage every `duration`" (e.g. every 1s), which i think matches how poison tends to work in other games?
2. as far as UI: we might want to add a transparency (reduce alpha) to the gas and put it's z-axis in the front -- right now e.g. the spawn points are in front of it.

Longer term thoughts:
1. what will cause the noxious gas to spawn? (randomly? a player pickup? always in the level?) 
2. It looks like the particular effect gets quite big. Might we allow passing a size boundary, e.g. `m x n` tiles, so you can make it a single tile, a wide pit, a tall tower, etc?

Happy to merge as is. But would love to get it operating in a game level too! If you'd prefer to iterate in the PR or merge and make another one, please work however is best for you.

**Comment by nathanleiby** [comment]
Gif of my testing, just to record the feature progress!
noxious-gas2

**Review by peternga — APPROVED** [review]
Very cool! I really like how the cloud slowly expands. I agree about the "can only damage x times per y seconds" but this is great.

**Comment by emmanent** [comment]
Got the transparency to work, and now the gas is rendered above the spawn points. I couldn't quite get a good "time to kill" just yet, so maybe that'll come in the future 😃

**Pull request merged**
